//! SD-loaded Unicode Reader font packs for Indic EPUB text.
//!
//! Rustmix Wave keeps Latin UI and Reader strikes embedded, but loads shaped
//! Devanagari and Gujarati cluster bitmaps from removable storage. The browser
//! font builder renders clusters with the user's locally supplied Noto Sans
//! fonts and writes bounded `.RWF` packs. Raw font files are never required on
//! the device and are intentionally not distributed in this repository.

use std::{
    fs,
    fs::File,
    io::{BufReader, Read, Seek, SeekFrom},
    path::Path,
};

use crate::reader::BookFontSize;

/// SD-card root for optional Reader Unicode font packs.
pub const READER_FONTS_DIRECTORY: &str = "/sdcard/RUSTMIX/FONTS";
/// FAT-safe manifest file selecting one pack per script and Reader size.
pub const READER_FONT_MANIFEST_FILE: &str = "FONTS.TXT";
/// Maximum bytes accepted for one generated pack.
pub const READER_FONT_PACK_MAX_BYTES: usize = 1024 * 1024;
/// Maximum shaped glyph clusters accepted from one pack.
pub const READER_FONT_GLYPH_LIMIT: usize = 8192;
/// Maximum UTF-8 bytes accepted for one shaped cluster key.
pub const READER_FONT_CLUSTER_MAX_BYTES: usize = 64;
/// Maximum visible-page glyph subset retained in RAM from one SD font pack.
pub const READER_FONT_PAGE_GLYPH_LIMIT: usize = 2048;

const RWF_MAGIC: &[u8; 4] = b"RWF1";

/// Script families supported by SD-loaded Reader packs.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ReaderUnicodeScript {
    Devanagari,
    Gujarati,
}

impl ReaderUnicodeScript {
    #[must_use]
    pub const fn manifest_label(self) -> &'static str {
        match self {
            Self::Devanagari => "DEVANAGARI",
            Self::Gujarati => "GUJARATI",
        }
    }

    fn from_binary_tag(value: u8) -> Result<Self, String> {
        match value {
            1 => Ok(Self::Devanagari),
            2 => Ok(Self::Gujarati),
            _ => Err(format!("unsupported RWF script tag {value}")),
        }
    }
}

/// Summary of scripts present in one flattened Reader document.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct ReaderScriptSummary {
    pub devanagari: bool,
    pub gujarati: bool,
    pub unsupported_non_ascii: bool,
}

impl ReaderScriptSummary {
    #[must_use]
    pub const fn has_indic(self) -> bool {
        self.devanagari || self.gujarati
    }

    #[must_use]
    pub const fn label(self) -> &'static str {
        match (self.devanagari, self.gujarati, self.unsupported_non_ascii) {
            (false, false, false) => "LATIN",
            (true, false, false) => "DEVA",
            (false, true, false) => "GUJ",
            (true, true, false) => "INDIC",
            _ => "UNICODE",
        }
    }
}

/// One shaped cluster bitmap generated by the browser font builder.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReaderUnicodeGlyph {
    pub sequence: String,
    pub width: u16,
    pub height: u16,
    pub advance: i16,
    pub left: i16,
    pub top: i16,
    pub bitmap: Vec<u8>,
}

/// One Reader-size font pack loaded from SD.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReaderUnicodeFontPack {
    pub script: ReaderUnicodeScript,
    pub size: BookFontSize,
    pub line_height: u16,
    pub glyphs: Vec<ReaderUnicodeGlyph>,
}

impl ReaderUnicodeFontPack {
    pub fn parse(bytes: &[u8]) -> Result<Self, String> {
        if bytes.len() > READER_FONT_PACK_MAX_BYTES {
            return Err(format!(
                "Unicode font pack exceeds {} byte limit",
                READER_FONT_PACK_MAX_BYTES
            ));
        }
        let mut cursor = Cursor::new(bytes);
        if cursor.take(4)? != RWF_MAGIC {
            return Err("Unicode font pack magic must be RWF1".into());
        }
        let script = ReaderUnicodeScript::from_binary_tag(cursor.u8()?)?;
        let size = font_size_from_tag(cursor.u8()?)?;
        let line_height = cursor.u16()?;
        let glyph_count = usize::try_from(cursor.u32()?)
            .map_err(|_| "Unicode glyph count exceeds platform range".to_string())?;
        if glyph_count > READER_FONT_GLYPH_LIMIT {
            return Err(format!(
                "Unicode font pack exceeds {} glyph limit",
                READER_FONT_GLYPH_LIMIT
            ));
        }
        let mut glyphs = Vec::with_capacity(glyph_count);
        for _ in 0..glyph_count {
            let sequence_bytes = usize::from(cursor.u16()?);
            if sequence_bytes == 0 || sequence_bytes > READER_FONT_CLUSTER_MAX_BYTES {
                return Err("Unicode glyph cluster key is empty or too large".into());
            }
            let width = cursor.u16()?;
            let height = cursor.u16()?;
            let advance = cursor.i16()?;
            let left = cursor.i16()?;
            let top = cursor.i16()?;
            let bitmap_bytes = usize::try_from(cursor.u32()?)
                .map_err(|_| "Unicode glyph bitmap exceeds platform range".to_string())?;
            let sequence = std::str::from_utf8(cursor.take(sequence_bytes)?)
                .map_err(|_| "Unicode glyph key is not UTF-8".to_string())?
                .to_string();
            let bitmap = cursor.take(bitmap_bytes)?.to_vec();
            let expected = (usize::from(width) + 7) / 8 * usize::from(height);
            if bitmap.len() != expected {
                return Err("Unicode glyph bitmap length does not match geometry".into());
            }
            glyphs.push(ReaderUnicodeGlyph {
                sequence,
                width,
                height,
                advance,
                left,
                top,
                bitmap,
            });
        }
        if !cursor.remaining().is_empty() {
            return Err("Unicode font pack has trailing bytes".into());
        }
        glyphs.sort_by(|left, right| right.sequence.len().cmp(&left.sequence.len()));
        Ok(Self {
            script,
            size,
            line_height,
            glyphs,
        })
    }

    #[must_use]
    pub fn longest_prefix(&self, text: &str) -> Option<&ReaderUnicodeGlyph> {
        self.glyphs
            .iter()
            .find(|glyph| text.starts_with(glyph.sequence.as_str()))
    }
}

/// Optional script packs loaded for the active Reader session.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ReaderUnicodeFonts {
    pub devanagari: Option<ReaderUnicodeFontPack>,
    pub gujarati: Option<ReaderUnicodeFontPack>,
    pub warning: Option<String>,
}

impl ReaderUnicodeFonts {
    #[must_use]
    pub fn load_page_best_effort(
        root: &Path,
        size: BookFontSize,
        scripts: ReaderScriptSummary,
        page_text: &str,
    ) -> Self {
        if !scripts.has_indic() {
            return Self::default();
        }
        match load_manifest(root) {
            Ok(rows) => {
                let mut warnings = Vec::new();
                let devanagari = if scripts.devanagari {
                    load_selected_page_pack(
                        root,
                        &rows,
                        ReaderUnicodeScript::Devanagari,
                        size,
                        page_text,
                    )
                    .map_err(|error| warnings.push(error))
                    .ok()
                } else {
                    None
                };
                let gujarati = if scripts.gujarati {
                    load_selected_page_pack(
                        root,
                        &rows,
                        ReaderUnicodeScript::Gujarati,
                        size,
                        page_text,
                    )
                    .map_err(|error| warnings.push(error))
                    .ok()
                } else {
                    None
                };
                Self {
                    devanagari,
                    gujarati,
                    warning: (!warnings.is_empty()).then(|| warnings.join("; ")),
                }
            }
            Err(error) => Self {
                devanagari: None,
                gujarati: None,
                warning: Some(error),
            },
        }
    }

    #[must_use]
    pub fn loaded_glyph_count(&self) -> usize {
        self.devanagari.as_ref().map_or(0, |pack| pack.glyphs.len())
            + self.gujarati.as_ref().map_or(0, |pack| pack.glyphs.len())
    }

    #[must_use]
    pub fn missing_required(&self, scripts: ReaderScriptSummary) -> bool {
        (scripts.devanagari && self.devanagari.is_none())
            || (scripts.gujarati && self.gujarati.is_none())
    }

    #[must_use]
    pub fn line_height(&self, latin_line_height: u8) -> u16 {
        let devanagari = self.devanagari.as_ref().map_or(0, |pack| pack.line_height);
        let gujarati = self.gujarati.as_ref().map_or(0, |pack| pack.line_height);
        u16::from(latin_line_height).max(devanagari).max(gujarati)
    }

    #[must_use]
    pub fn status_label(&self, scripts: ReaderScriptSummary) -> &'static str {
        if !scripts.has_indic() {
            scripts.label()
        } else if self.missing_required(scripts) {
            "FONT?"
        } else {
            scripts.label()
        }
    }

    #[must_use]
    pub fn longest_prefix(&self, text: &str) -> Option<&ReaderUnicodeGlyph> {
        let first = text.chars().next()?;
        if is_devanagari_character(first) || is_vedic_character(first) {
            return self
                .devanagari
                .as_ref()
                .and_then(|pack| pack.longest_prefix(text));
        }
        if is_gujarati_character(first) {
            return self
                .gujarati
                .as_ref()
                .and_then(|pack| pack.longest_prefix(text));
        }
        None
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct ReaderUnicodeManifestRow {
    script: ReaderUnicodeScript,
    size: BookFontSize,
    file_name: String,
}

fn load_manifest(root: &Path) -> Result<Vec<ReaderUnicodeManifestRow>, String> {
    let path = root.join(READER_FONT_MANIFEST_FILE);
    let text = fs::read_to_string(&path)
        .map_err(|error| format!("{} missing or unreadable: {error}", path.display()))?;
    let mut rows = Vec::new();
    for (line_number, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let fields = line.split('|').map(str::trim).collect::<Vec<_>>();
        if fields.len() != 3 {
            return Err(format!(
                "FONTS.TXT line {} must have 3 fields",
                line_number + 1
            ));
        }
        let script = match fields[0].to_ascii_uppercase().as_str() {
            "DEVANAGARI" => ReaderUnicodeScript::Devanagari,
            "GUJARATI" => ReaderUnicodeScript::Gujarati,
            other => {
                return Err(format!(
                    "FONTS.TXT line {} unknown script {other}",
                    line_number + 1
                ))
            }
        };
        let size = parse_font_size(fields[1])?;
        let file_name = fields[2].to_ascii_uppercase();
        if !is_fat83_rwf_file_name(&file_name) {
            return Err(format!(
                "FONTS.TXT line {} path is not FAT 8.3 RWF",
                line_number + 1
            ));
        }
        rows.push(ReaderUnicodeManifestRow {
            script,
            size,
            file_name,
        });
    }
    Ok(rows)
}

fn load_selected_page_pack(
    root: &Path,
    rows: &[ReaderUnicodeManifestRow],
    script: ReaderUnicodeScript,
    size: BookFontSize,
    page_text: &str,
) -> Result<ReaderUnicodeFontPack, String> {
    let row = rows
        .iter()
        .find(|row| row.script == script && row.size == size)
        .ok_or_else(|| {
            format!(
                "FONTS.TXT has no {} {} pack",
                script.manifest_label(),
                size.marker()
            )
        })?;
    let path = root.join(&row.file_name);
    parse_page_subset_file(&path, script, size, page_text)
}

fn parse_page_subset_file(
    path: &Path,
    expected_script: ReaderUnicodeScript,
    expected_size: BookFontSize,
    page_text: &str,
) -> Result<ReaderUnicodeFontPack, String> {
    let file =
        File::open(path).map_err(|error| format!("{} unreadable: {error}", path.display()))?;
    let file_len = usize::try_from(
        file.metadata()
            .map_err(|error| format!("{} metadata failed: {error}", path.display()))?
            .len(),
    )
    .map_err(|_| format!("{} size exceeds platform range", path.display()))?;
    if file_len > READER_FONT_PACK_MAX_BYTES {
        return Err(format!(
            "{} exceeds {} byte limit",
            path.display(),
            READER_FONT_PACK_MAX_BYTES
        ));
    }
    let mut reader = BufReader::new(file);
    let mut magic = [0_u8; 4];
    reader
        .read_exact(&mut magic)
        .map_err(|error| format!("{} header read failed: {error}", path.display()))?;
    if &magic != RWF_MAGIC {
        return Err(format!("{} magic must be RWF1", path.display()));
    }
    let script = ReaderUnicodeScript::from_binary_tag(read_stream_u8(&mut reader)?)?;
    let size = font_size_from_tag(read_stream_u8(&mut reader)?)?;
    let line_height = read_stream_u16(&mut reader)?;
    let glyph_count = usize::try_from(read_stream_u32(&mut reader)?)
        .map_err(|_| "Unicode glyph count exceeds platform range".to_string())?;
    if glyph_count > READER_FONT_GLYPH_LIMIT {
        return Err(format!(
            "{} exceeds {} glyph limit",
            path.display(),
            READER_FONT_GLYPH_LIMIT
        ));
    }
    if script != expected_script || size != expected_size {
        return Err(format!(
            "{} metadata does not match FONTS.TXT",
            path.display()
        ));
    }

    let mut glyphs = Vec::new();
    for _ in 0..glyph_count {
        let sequence_bytes = usize::from(read_stream_u16(&mut reader)?);
        if sequence_bytes == 0 || sequence_bytes > READER_FONT_CLUSTER_MAX_BYTES {
            return Err("Unicode glyph cluster key is empty or too large".into());
        }
        let width = read_stream_u16(&mut reader)?;
        let height = read_stream_u16(&mut reader)?;
        let advance = read_stream_i16(&mut reader)?;
        let left = read_stream_i16(&mut reader)?;
        let top = read_stream_i16(&mut reader)?;
        let bitmap_bytes = usize::try_from(read_stream_u32(&mut reader)?)
            .map_err(|_| "Unicode glyph bitmap exceeds platform range".to_string())?;
        let expected_bitmap_bytes = (usize::from(width) + 7) / 8 * usize::from(height);
        if bitmap_bytes != expected_bitmap_bytes {
            return Err("Unicode glyph bitmap length does not match geometry".into());
        }
        let mut sequence_bytes_buf = vec![0_u8; sequence_bytes];
        reader
            .read_exact(&mut sequence_bytes_buf)
            .map_err(|error| format!("{} glyph key read failed: {error}", path.display()))?;
        let sequence = std::str::from_utf8(&sequence_bytes_buf)
            .map_err(|_| "Unicode glyph key is not UTF-8".to_string())?;
        if page_text.contains(sequence) {
            if glyphs.len() >= READER_FONT_PAGE_GLYPH_LIMIT {
                return Err(format!(
                    "{} visible page exceeds {} glyph subset limit",
                    path.display(),
                    READER_FONT_PAGE_GLYPH_LIMIT
                ));
            }
            let mut bitmap = vec![0_u8; bitmap_bytes];
            reader
                .read_exact(&mut bitmap)
                .map_err(|error| format!("{} glyph bitmap read failed: {error}", path.display()))?;
            glyphs.push(ReaderUnicodeGlyph {
                sequence: sequence.to_string(),
                width,
                height,
                advance,
                left,
                top,
                bitmap,
            });
        } else {
            reader
                .seek(SeekFrom::Current(i64::try_from(bitmap_bytes).map_err(
                    |_| "Unicode glyph bitmap skip exceeds platform range".to_string(),
                )?))
                .map_err(|error| format!("{} glyph bitmap skip failed: {error}", path.display()))?;
        }
    }
    let consumed = usize::try_from(
        reader
            .stream_position()
            .map_err(|error| format!("{} position read failed: {error}", path.display()))?,
    )
    .map_err(|_| "Unicode font-pack position exceeds platform range".to_string())?;
    if consumed != file_len {
        return Err(format!("{} has trailing bytes", path.display()));
    }
    glyphs.sort_by(|left, right| right.sequence.len().cmp(&left.sequence.len()));
    Ok(ReaderUnicodeFontPack {
        script,
        size,
        line_height,
        glyphs,
    })
}

fn read_stream_u8(reader: &mut impl Read) -> Result<u8, String> {
    let mut bytes = [0_u8; 1];
    reader
        .read_exact(&mut bytes)
        .map_err(|error| format!("Unicode font-pack byte read failed: {error}"))?;
    Ok(bytes[0])
}

fn read_stream_u16(reader: &mut impl Read) -> Result<u16, String> {
    let mut bytes = [0_u8; 2];
    reader
        .read_exact(&mut bytes)
        .map_err(|error| format!("Unicode font-pack u16 read failed: {error}"))?;
    Ok(u16::from_le_bytes(bytes))
}

fn read_stream_i16(reader: &mut impl Read) -> Result<i16, String> {
    let mut bytes = [0_u8; 2];
    reader
        .read_exact(&mut bytes)
        .map_err(|error| format!("Unicode font-pack i16 read failed: {error}"))?;
    Ok(i16::from_le_bytes(bytes))
}

fn read_stream_u32(reader: &mut impl Read) -> Result<u32, String> {
    let mut bytes = [0_u8; 4];
    reader
        .read_exact(&mut bytes)
        .map_err(|error| format!("Unicode font-pack u32 read failed: {error}"))?;
    Ok(u32::from_le_bytes(bytes))
}

#[must_use]
pub fn detect_reader_scripts(text: &str) -> ReaderScriptSummary {
    let mut summary = ReaderScriptSummary::default();
    for character in text.chars() {
        if is_devanagari_character(character) || is_vedic_character(character) {
            summary.devanagari = true;
        } else if is_gujarati_character(character) {
            summary.gujarati = true;
        } else if !is_latin_or_common_character(character) {
            summary.unsupported_non_ascii = true;
        }
    }
    summary
}

#[must_use]
pub fn preserve_reader_unicode_character(character: char) -> bool {
    is_devanagari_character(character)
        || is_gujarati_character(character)
        || is_vedic_character(character)
        || matches!(character, '\u{200C}' | '\u{200D}' | '\u{0964}' | '\u{0965}')
}

#[must_use]
pub fn reader_cluster_count(text: &str) -> usize {
    let mut count = 0;
    let mut previous = None;
    for character in text.chars() {
        if !continues_reader_cluster(previous, character) {
            count += 1;
        }
        previous = Some(character);
    }
    count
}

#[must_use]
pub fn continues_reader_cluster(previous: Option<char>, current: char) -> bool {
    let Some(previous) = previous else {
        return false;
    };
    is_indic_combining_mark(current)
        || is_vedic_character(current)
        || matches!(current, '\u{200C}' | '\u{200D}')
        || is_indic_virama(previous)
}

#[must_use]
pub const fn is_devanagari_character(character: char) -> bool {
    matches!(character as u32, 0x0900..=0x097F | 0xA8E0..=0xA8FF)
}

#[must_use]
pub const fn is_gujarati_character(character: char) -> bool {
    matches!(character as u32, 0x0A80..=0x0AFF)
}

#[must_use]
pub const fn is_vedic_character(character: char) -> bool {
    matches!(character as u32, 0x1CD0..=0x1CFF)
}

#[must_use]
const fn is_indic_combining_mark(character: char) -> bool {
    matches!(
        character as u32,
        0x0900..=0x0903
            | 0x093A..=0x094F
            | 0x0951..=0x0957
            | 0x0962..=0x0963
            | 0x0A81..=0x0A83
            | 0x0ABC
            | 0x0ABE..=0x0ACD
            | 0x0AE2..=0x0AE3
    )
}

#[must_use]
const fn is_indic_virama(character: char) -> bool {
    matches!(character, '\u{094D}' | '\u{0ACD}')
}

#[must_use]
fn is_latin_or_common_character(character: char) -> bool {
    character.is_ascii()
        || character.is_whitespace()
        || matches!(
            character as u32,
            0x00A0..=0x024F | 0x2000..=0x206F | 0x20A0..=0x20CF
        )
}

fn parse_font_size(value: &str) -> Result<BookFontSize, String> {
    match value.trim().to_ascii_uppercase().as_str() {
        "SMALL" => Ok(BookFontSize::Small),
        "MEDIUM" => Ok(BookFontSize::Medium),
        "LARGE" => Ok(BookFontSize::Large),
        "XLARGE" => Ok(BookFontSize::XLarge),
        other => Err(format!("unsupported Reader font-pack size {other}")),
    }
}

fn font_size_from_tag(value: u8) -> Result<BookFontSize, String> {
    match value {
        0 => Ok(BookFontSize::Small),
        1 => Ok(BookFontSize::Medium),
        2 => Ok(BookFontSize::Large),
        3 => Ok(BookFontSize::XLarge),
        _ => Err(format!("unsupported RWF size tag {value}")),
    }
}

#[must_use]
fn is_fat83_rwf_file_name(value: &str) -> bool {
    let Some((base, extension)) = value.split_once('.') else {
        return false;
    };
    !base.is_empty()
        && base.len() <= 8
        && base
            .bytes()
            .all(|byte| byte.is_ascii_uppercase() || byte.is_ascii_digit())
        && extension == "RWF"
}

struct Cursor<'a> {
    bytes: &'a [u8],
    offset: usize,
}

impl<'a> Cursor<'a> {
    const fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, offset: 0 }
    }

    fn remaining(&self) -> &'a [u8] {
        &self.bytes[self.offset..]
    }

    fn take(&mut self, count: usize) -> Result<&'a [u8], String> {
        let end = self
            .offset
            .checked_add(count)
            .ok_or_else(|| "Unicode font-pack cursor overflow".to_string())?;
        let bytes = self
            .bytes
            .get(self.offset..end)
            .ok_or_else(|| "Unicode font pack is truncated".to_string())?;
        self.offset = end;
        Ok(bytes)
    }

    fn u8(&mut self) -> Result<u8, String> {
        Ok(self.take(1)?[0])
    }

    fn u16(&mut self) -> Result<u16, String> {
        let bytes = self.take(2)?;
        Ok(u16::from_le_bytes([bytes[0], bytes[1]]))
    }

    fn i16(&mut self) -> Result<i16, String> {
        let bytes = self.take(2)?;
        Ok(i16::from_le_bytes([bytes[0], bytes[1]]))
    }

    fn u32(&mut self) -> Result<u32, String> {
        let bytes = self.take(4)?;
        Ok(u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]))
    }
}

#[cfg(test)]
mod tests {
    use std::{fs, path::PathBuf};

    use super::{
        detect_reader_scripts, preserve_reader_unicode_character, reader_cluster_count,
        ReaderScriptSummary, ReaderUnicodeFontPack, ReaderUnicodeFonts,
    };
    use crate::reader::BookFontSize;

    fn temp_root(name: &str) -> PathBuf {
        let root = std::env::temp_dir().join(format!(
            "rustmix-unicode-font-{name}-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(&root).unwrap();
        root
    }

    fn sample_pack(sequence: &str) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(b"RWF1");
        bytes.push(1);
        bytes.push(1);
        bytes.extend_from_slice(&24_u16.to_le_bytes());
        bytes.extend_from_slice(&1_u32.to_le_bytes());
        bytes.extend_from_slice(&(sequence.len() as u16).to_le_bytes());
        bytes.extend_from_slice(&8_u16.to_le_bytes());
        bytes.extend_from_slice(&8_u16.to_le_bytes());
        bytes.extend_from_slice(&9_i16.to_le_bytes());
        bytes.extend_from_slice(&0_i16.to_le_bytes());
        bytes.extend_from_slice(&(-8_i16).to_le_bytes());
        bytes.extend_from_slice(&8_u32.to_le_bytes());
        bytes.extend_from_slice(sequence.as_bytes());
        bytes.extend_from_slice(&[0xFF; 8]);
        bytes
    }

    #[test]
    fn detects_devanagari_gujarati_and_mixed_text() {
        assert_eq!(
            detect_reader_scripts("श्रीकृष्ण"),
            ReaderScriptSummary {
                devanagari: true,
                gujarati: false,
                unsupported_non_ascii: false,
            }
        );
        assert!(detect_reader_scripts("વાલ્મીકી").gujarati);
        let mixed = detect_reader_scripts("श्री વાલ્મીકી");
        assert!(mixed.devanagari && mixed.gujarati);
    }

    #[test]
    fn preserves_indic_unicode_and_counts_clusters_without_splitting_virama() {
        assert!(preserve_reader_unicode_character('क'));
        assert!(preserve_reader_unicode_character('ી'));
        assert_eq!(reader_cluster_count("कि"), 1);
        assert_eq!(reader_cluster_count("श्री"), 1);
        assert_eq!(reader_cluster_count("ક્ષ"), 1);
    }

    #[test]
    fn parses_bounded_cluster_pack_and_loads_manifest_selection() {
        let root = temp_root("pack");
        fs::write(root.join("NSD14.RWF"), sample_pack("श्री")).unwrap();
        fs::write(root.join("FONTS.TXT"), "DEVANAGARI|MEDIUM|NSD14.RWF\n").unwrap();
        let parsed = ReaderUnicodeFontPack::parse(&sample_pack("श्री")).unwrap();
        assert_eq!(parsed.glyphs[0].sequence, "श्री");
        let fonts = ReaderUnicodeFonts::load_page_best_effort(
            &root,
            BookFontSize::Medium,
            ReaderScriptSummary {
                devanagari: true,
                gujarati: false,
                unsupported_non_ascii: false,
            },
            "श्रीकृष्ण",
        );
        assert_eq!(fonts.longest_prefix("श्रीकृष्ण").unwrap().sequence, "श्री");
        fs::remove_dir_all(root).unwrap();
    }
}
